import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { MotionValue } from 'framer-motion';
import { useUserStore } from '../../store/userStore';

export const DISCLAIMER_TEXT = `About The Game
At Your Age (AYA) is an interactive personality discovery game designed for entertainment and personal reflection purposes only. The scenarios, stories and personality assessments presented in this app are fictional simulations inspired by publicly available historical information and are not intended to be factually comprehensive or academically verified.

About Personality Assessments
The personality profiles, DNA reports, trait scores, Future Self predictions and archetype matches generated by AYA are based on in-game decisions and quiz responses. They are designed for entertainment and self-reflection only. They do not constitute professional psychological assessments, career advice, mental health evaluations or any form of clinical diagnosis. Results should not be used as the basis for any major life decisions.

About Real People
AYA features fictional game scenarios inspired by the lives of real public figures. These scenarios are creative interpretations and simulations — they do not claim to accurately represent the actual thoughts, decisions, beliefs or private lives of any individual. All dialogue and choices presented are fictional. Resemblance to actual events is used for inspirational and educational purposes only.

About User Data
AYA collects basic user information including name, age and mobile number to personalize your experience. We collect behavioral data including quiz responses, in-game choices and session data to improve our recommendations. We do not sell individual personal data to third parties. Aggregated and anonymized insights may be used for research and product improvement. By using AYA you consent to the collection and use of this data as described in our Privacy Policy.

About Push Notifications
If you enable push notifications AYA may send you daily reminders and motivational messages. You can disable notifications at any time through your device settings.

Age Requirement
AYA is designed for users aged 13 and above. Users under 18 should use this app with parental awareness. We do not knowingly collect personal information from children under 13.

Mental Health Notice
Some story scenarios may touch on themes including failure, rejection, loss, loneliness and emotional struggle. These are presented in an educational and motivational context. If you are experiencing mental health difficulties please seek support from a qualified professional.

No Guarantees
AYA makes no guarantees about the accuracy of personality assessments, future self predictions or archetype matches. These features are designed to inspire reflection and curiosity — not to predict your actual future.

Contact
For questions or concerns about this disclaimer or your data please contact us at: atyourage@gmail.com
Last updated: April 2026`;

// Virtualized Frame Manager to fix the RAM issue
class FrameManager {
    private folder: string;
    private totalFrames: number;
    private cache: Map<number, HTMLImageElement> = new Map();
    private loading: Set<number> = new Set();
    private currentFrameIndex: number = -1;
    private bufferSizeAhead = 15; // Reduced from 60 to prevent RAM crash
    private bufferSizeBehind = 5; // Reduced from 30 to prevent RAM crash

    constructor(folder: string, totalFrames: number) {
        this.folder = folder;
        this.totalFrames = totalFrames;
    }

    public preloadInitial(count: number = 30, onProgress: (loaded: number) => void, onComplete: () => void) {
        let loaded = 0;
        const target = Math.min(count, this.totalFrames);
        for (let i = 0; i < target; i++) {
            this.loadFrame(i, () => {
                loaded++;
                onProgress(loaded);
                if (loaded === target) onComplete();
            });
        }
    }

    private loadFrame(index: number, onLoaded?: () => void) {
        if (this.cache.has(index) || this.loading.has(index)) {
            if (this.cache.has(index) && onLoaded) onLoaded();
            return;
        }

        this.loading.add(index);
        const img = new Image();
        img.src = `/assets/${this.folder}/ezgif-frame-${(index + 1).toString().padStart(3, '0')}.jpg`;
        img.onload = () => {
            this.cache.set(index, img);
            this.loading.delete(index);
            if (onLoaded) onLoaded();
        };
        img.onerror = () => {
            this.loading.delete(index);
            if (onLoaded) onLoaded();
        };
    }

    public updateTargetFrame(index: number) {
        if (this.currentFrameIndex === index) return;
        this.currentFrameIndex = index;

        // Prefetch nearby frames aggressively
        for (let i = index - 10; i <= index + this.bufferSizeAhead; i++) {
            if (i >= 0 && i < this.totalFrames) {
                this.loadFrame(i);
            }
        }

        // Evict old frames to free RAM (only outside our safe window)
        for (const [key] of this.cache.entries()) {
            if (key < index - this.bufferSizeBehind || key > index + this.bufferSizeAhead + 10) {
                this.cache.delete(key);
            }
        }
    }

    public getFrame(index: number): HTMLImageElement | undefined {
        return this.cache.get(index);
    }
    
    public cleanup() {
        this.cache.clear();
        this.loading.clear();
    }
}

interface AntiGravityCanvasProps {
    progress: MotionValue<number>;
    onReady: () => void;
}

export function AntiGravityCanvas({ progress, onReady }: AntiGravityCanvasProps) {
    const isCandyMode = useUserStore((state) => state.isCandyMode);
    const setIntroVideoCompleted = useUserStore((state) => state.setIntroVideoCompleted);
    const totalFrames = isCandyMode ? 40 : 240;
    const folder = isCandyMode ? 'map_frames' : 'map_frames_dark';

    const canvasRef = useRef<HTMLCanvasElement>(null);
    const frameManager = useRef<FrameManager | null>(null);
    const [imagesLoaded, setImagesLoaded] = useState(0);
    const [isReady, setIsReady] = useState(false);
    
    // We only track progress to draw
    const lastDrawnIndexRef = useRef<number>(-1);
    const loopRef = useRef<number>(0);

    useEffect(() => {
        setIntroVideoCompleted(false);
        setImagesLoaded(0);

        if (frameManager.current) {
            frameManager.current.cleanup();
        }

        const manager = new FrameManager(folder, totalFrames);
        frameManager.current = manager;

        manager.preloadInitial(
            30, 
            (loaded) => setImagesLoaded(loaded),
            () => {
                setIsReady(true);
                setIntroVideoCompleted(true);
                onReady();
            }
        );

        return () => {
            if (frameManager.current) frameManager.current.cleanup();
        };
    }, [folder, totalFrames, setIntroVideoCompleted, onReady]);

    useEffect(() => {
        if (!isReady || !canvasRef.current || !frameManager.current) return;

        const canvas = canvasRef.current;
        const ctx = canvas.getContext('2d', { alpha: false });
        if (!ctx) return;

        let canvasWidth = window.innerWidth;
        let canvasHeight = window.innerHeight;
        let dpr = window.devicePixelRatio || 1;

        const setupCanvasContext = () => {
            canvasWidth = window.innerWidth;
            canvasHeight = window.innerHeight;
            dpr = window.devicePixelRatio || 1;

            canvas.width = canvasWidth * dpr;
            canvas.height = canvasHeight * dpr;
            canvas.style.width = `${canvasWidth}px`;
            canvas.style.height = `${canvasHeight}px`;

            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
        };

        setupCanvasContext();

        const renderNativeFrame = (index: number) => {
            const safeIndex = Math.max(0, Math.min(totalFrames - 1, index));
            
            frameManager.current?.updateTargetFrame(safeIndex);
            
            const img = frameManager.current?.getFrame(safeIndex);
            if (!img || !img.complete) return; // Wait until loaded

            const canvasRatio = (canvasWidth * dpr) / (canvasHeight * dpr);
            const imgRatio = img.width / img.height;

            let drawWidth = canvasWidth * dpr;
            let drawHeight = canvasHeight * dpr;
            let offsetX = 0;
            let offsetY = 0;

            if (canvasRatio > imgRatio) {
                drawHeight = (canvasWidth * dpr) / imgRatio;
                offsetY = ((canvasHeight * dpr) - drawHeight) / 2;
            } else {
                drawWidth = (canvasHeight * dpr) * imgRatio;
                offsetX = ((canvasWidth * dpr) - drawWidth) / 2;
            }

            ctx.drawImage(img, offsetX, offsetY, drawWidth, drawHeight);
        };

        const handleResize = () => {
            setupCanvasContext();
            lastDrawnIndexRef.current = -1; // Force redraw
        };
        window.addEventListener('resize', handleResize);

        const tick = () => {
            const currentProgress = progress.get() || 0; 
            const index = Math.floor(currentProgress * (totalFrames - 1));
            const safeTarget = Math.max(0, Math.min(totalFrames - 1, index));

            // Only update target frame & compute nearest frame if target frame index changed
            if (safeTarget !== lastDrawnIndexRef.current) {
                frameManager.current?.updateTargetFrame(safeTarget);

                // Try to find the closest loaded frame to prevent visual freezing
                let bestImg = null;
                let bestIndex = -1;

                // Search outwards from target index to find the nearest loaded frame
                for (let offset = 0; offset <= 20; offset++) {
                    // Try exact or ahead
                    let checkIdx = Math.min(totalFrames - 1, safeTarget + offset);
                    let img = frameManager.current?.getFrame(checkIdx);
                    if (img && img.complete) {
                        bestImg = img;
                        bestIndex = checkIdx;
                        break;
                    }
                    
                    // Try behind
                    if (offset > 0) {
                        checkIdx = Math.max(0, safeTarget - offset);
                        img = frameManager.current?.getFrame(checkIdx);
                        if (img && img.complete) {
                            bestImg = img;
                            bestIndex = checkIdx;
                            break;
                        }
                    }
                }

                if (bestImg && bestIndex !== lastDrawnIndexRef.current) {
                    renderNativeFrame(bestIndex);
                    lastDrawnIndexRef.current = bestIndex;
                }
            }

            loopRef.current = requestAnimationFrame(tick);
        };

        // Initial draw setup
        const initialProgress = progress.get() || 0;
        const initialIndex = Math.floor(initialProgress * (totalFrames - 1));
        renderNativeFrame(initialIndex);
        lastDrawnIndexRef.current = initialIndex;
        tick();

        return () => {
            window.removeEventListener('resize', handleResize);
            cancelAnimationFrame(loopRef.current);
        };
    }, [isReady, progress, totalFrames]);

    return (
        <>
            {!isReady && createPortal(
                <div className="fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-[#050814]">
                    <div className="absolute bottom-1/2 translate-y-1/2 flex flex-col items-center text-cyan-400 font-mono tracking-widest font-bold z-10 w-64 max-w-[80%]">
                        <div className="text-sm mb-4 animate-pulse">INITIATING TIMELINE...</div>
                        <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden shadow-[0_0_15px_rgba(0,241,254,0.3)]">
                            <div
                                className="h-full bg-cyan-400 transition-all duration-200"
                                style={{ width: `${(imagesLoaded / 30) * 100}%` }}
                            />
                        </div>
                    </div>
                </div>,
                document.body
            )}
            <canvas
                ref={canvasRef}
                className="fixed top-0 left-0 w-full h-full pointer-events-none z-0"
            />
        </>
    );
}
