-- ============================================================
-- Complete AYA Story Metadata Seed Script (All 78 Active Stories)
-- ============================================================
-- Generated automatically from levelGenerator.ts and scenarios.ts
-- Idempotent: uses INSERT INTO public.story_metadata ... ON CONFLICT (story_id) DO UPDATE
-- Valid Postgres ARRAY[...] & JSONB formatting
-- ============================================================

INSERT INTO public.story_metadata (
    story_id,
    situation_tags,
    problem_tags,
    emotional_tags,
    intent_tags,
    life_stage_tags,
    age_min,
    age_max,
    dominant_trait,
    trait_affinity,
    resolution_archetype,
    lesson_tags,
    difficulty,
    relatability,
    era,
    cultural_context,
    semantic_description,
    trigger_phrases,
    best_for_mode,
    why_this_story_template,
    is_premium,
    premium_tier,
    created_at,
    updated_at
) VALUES
(
    'lvl_age_13_anne_1',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Anne Frank at age 13 navigating the notebook: At 13, Anne receives a diary for her birthday. What will she use it for?',
    ARRAY['anne frank', 'the notebook', 'anne frank age 13', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Anne Frank at age 13 faced a pivotal choice in The Notebook — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_13_anne_2',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Anne Frank at age 13 navigating when ordinary life disappears: Weeks later, Anne\',
    ARRAY['anne frank', 'when ordinary life disappears', 'anne frank age 13', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Anne Frank at age 13 faced a pivotal choice in When Ordinary Life Disappears — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_elon_musk',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Elon Musk at age 15 navigating the thing you love: At 15, Elon Musk navigates being a bookish, introverted teenager with a passion for computers and coding, deciding how to protect his interests.',
    ARRAY['elon musk', 'the thing you love', 'elon musk age 15', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Elon Musk at age 15 faced a pivotal choice in The Thing You Love — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_ratan_tata',
    ARRAY['career_uncertainty', 'identity_question', 'confidence_low'],
    ARRAY['isolation'],
    ARRAY['anxious'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'indian',
    'A story about Ratan Tata at age 15 navigating the quiet voice: At 15, Ratan Tata experiences shyness and fear of public speaking while attending school in Bombay, discovering how quiet self-expression can build confidence.',
    ARRAY['ratan tata', 'the quiet voice', 'ratan tata age 15', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Ratan Tata at age 15 faced a pivotal choice in The Quiet Voice — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_virat_kohli',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'indian',
    'A story about Virat Kohli at age 15 navigating more than your own score: At 15, Virat Kohli is appointed captain of Delhi Under-15, learning the balance between individual performance and team leadership.',
    ARRAY['virat kohli', 'more than your own score', 'virat kohli age 15', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Virat Kohli at age 15 faced a pivotal choice in More Than Your Own Score — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_michael_1',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'pivot',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Michael Jackson at age 15 navigating when your voice changes: At 15, Michael Jackson experiences physical and vocal changes during adolescence while continuing his music career.',
    ARRAY['michael jackson', 'when your voice changes', 'michael jackson age 15', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Michael Jackson at age 15 faced a pivotal choice in When Your Voice Changes — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_michael_2',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['teen'],
    13,
    18,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Michael Jackson at age 15 navigating when people expect the old you: At 15, Michael Jackson decides how to navigate audience expectations as he grows out of his childhood identity.',
    ARRAY['michael jackson', 'when people expect the old you', 'michael jackson age 15', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Michael Jackson at age 15 faced a pivotal choice in When People Expect the Old You — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_rani_lakshmibai',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Rani Lakshmibai at age 15 navigating the girl and the crown: At 15, Manikarnika becomes Lakshmibai, Rani of Jhansi, navigating the identity transition between her past and her new royal responsibilities.',
    ARRAY['rani lakshmibai', 'the girl and the crown', 'rani lakshmibai age 15', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Rani Lakshmibai at age 15 faced a pivotal choice in The Girl and the Crown — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_bhagat_1',
    ARRAY['starting_something'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'indian',
    'A story about Bhagat Singh at age 15 navigating don\: At 15, Bhagat Singh witnesses political tension in Lahore and learns how to channel anger into constructive learning and action.',
    ARRAY['bhagat singh', 'don\', 'bhagat singh age 15', 'starting_something'],
    'support',
    'You are dealing with {user_problem}. Bhagat Singh at age 15 faced a pivotal choice in Don\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_bhagat_2',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'indian',
    'A story about Bhagat Singh at age 15 navigating what if i\: At 15, Bhagat Singh learns intellectual humility and the importance of independent thinking when hearing opposing views.',
    ARRAY['bhagat singh', 'what if i\', 'bhagat singh age 15', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Bhagat Singh at age 15 faced a pivotal choice in What If I\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_15_ronaldo',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['lonely'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'adapt',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'global',
    'A story about Cristiano Ronaldo at age 15 navigating far from home: At 15, Cristiano Ronaldo experiences loneliness and homesickness in Lisbon after moving from Madeira, deciding whether to stay and persevere or return home.',
    ARRAY['cristiano ronaldo', 'far from home', 'cristiano ronaldo age 15', 'identity_question'],
    'challenge',
    'You are dealing with {user_problem}. Cristiano Ronaldo at age 15 faced a pivotal choice in Far From Home — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_billie_2',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Billie Eilish at age 20 navigating the person who left you on seen: At 20, you must choose between chasing someone who ghosts you, or turning the pain into art.',
    ARRAY['billie eilish', 'the person who left you on seen', 'billie eilish age 20', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Billie Eilish at age 20 faced a pivotal choice in The Person Who Left You On Seen — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_justin',
    ARRAY['starting_something', 'feeling_stuck'],
    ARRAY['isolation'],
    ARRAY['lonely'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Justin Bieber at age 19 navigating the hotel room at 2am: At 19, you sit alone in a hotel room deciding whether to text an ex or face the emptiness underneath.',
    ARRAY['justin bieber', 'the hotel room at 2am', 'justin bieber age 19', 'starting_something'],
    'support',
    'You are dealing with {user_problem}. Justin Bieber at age 19 faced a pivotal choice in The Hotel Room at 2AM — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_srk',
    ARRAY['exam_pressure', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Shah Rukh Khan at age 17 navigating the stage or the books: At 17, SRK faces an impossible choice — grieve, study, or chase the stage.',
    ARRAY['shah rukh khan', 'the stage or the books', 'shah rukh khan age 17', 'exam_pressure'],
    'support',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 17 faced a pivotal choice in The Stage or The Books — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_sindhu',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about P.V. Sindhu at age 17 navigating the olympic prelude: At 17, Sindhu faced the seemingly invincible Olympic gold medalist.',
    ARRAY['p.v. sindhu', 'the olympic prelude', 'p.v. sindhu age 17', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. P.V. Sindhu at age 17 faced a pivotal choice in The Olympic Prelude — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_rahman',
    ARRAY['family_pressure'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about A.R. Rahman at age 17 navigating the silent melody: At 17, a grieving son drops out of school to support his family through music.',
    ARRAY['a.r. rahman', 'the silent melody', 'a.r. rahman age 17', 'family_pressure'],
    'support',
    'You are dealing with {user_problem}. A.R. Rahman at age 17 faced a pivotal choice in The Silent Melody — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_malala',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Malala Yousafzai at age 17 navigating the price of peace: At 17, Malala won the Nobel Prize. But was the global spotlight worth the trauma?',
    ARRAY['malala yousafzai', 'the price of peace', 'malala yousafzai age 17', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Malala Yousafzai at age 17 faced a pivotal choice in The Price of Peace — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_jobs',
    ARRAY['career_uncertainty', 'failure_setback'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Steve Jobs at age 17 navigating the dropout\: At 17, Jobs dropped out of Harvard to audit calligraphy classes.',
    ARRAY['steve jobs', 'the dropout\', 'steve jobs age 17', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Steve Jobs at age 17 faced a pivotal choice in The Dropout\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_17_nooyi',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Indra Nooyi at age 17 navigating the rulebreaker: At 17, a young Indian woman played in an all-girls rock band and broke every conventional rule.',
    ARRAY['indra nooyi', 'the rulebreaker', 'indra nooyi age 17', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Indra Nooyi at age 17 faced a pivotal choice in The Rulebreaker — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'pivot',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Taylor Swift at age 18 navigating the beginning (country): At 18, Taylor faced a choice: Security or Authenticity.',
    ARRAY['taylor swift', 'the beginning (country)', 'taylor swift age 18', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Taylor Swift at age 18 faced a pivotal choice in The Beginning (Country) — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_zendaya',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Zendaya at age 18 navigating the identity strike: At 18, Zendaya risked her Disney career for creative control.',
    ARRAY['zendaya', 'the identity strike', 'zendaya age 18', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Zendaya at age 18 faced a pivotal choice in The Identity Strike — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_anand',
    ARRAY['starting_something'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Viswanathan Anand at age 18 navigating the lightning kid: At 18, Anand became India\',
    ARRAY['viswanathan anand', 'the lightning kid', 'viswanathan anand age 18', 'starting_something'],
    'challenge',
    'You are dealing with {user_problem}. Viswanathan Anand at age 18 faced a pivotal choice in The Lightning Kid — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_kohli',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Virat Kohli at age 18 navigating the hardest day: At 18, Virat faced the ultimate test of duty and grief.',
    ARRAY['virat kohli', 'the hardest day', 'virat kohli age 18', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Virat Kohli at age 18 faced a pivotal choice in The Hardest Day — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_virat',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Virat Kohli at age 18 navigating virat conversational: Experience Virat\',
    ARRAY['virat kohli', 'virat conversational', 'virat kohli age 18', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Virat Kohli at age 18 faced a pivotal choice in Virat Conversational — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_kalam',
    ARRAY['exam_pressure'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Dr. A.P.J. Abdul Kalam at age 18 navigating the big leap: At 18, Kalam left his humble town for a prestigious college.',
    ARRAY['dr. a.p.j. abdul kalam', 'the big leap', 'dr. a.p.j. abdul kalam age 18', 'exam_pressure'],
    'support',
    'You are dealing with {user_problem}. Dr. A.P.J. Abdul Kalam at age 18 faced a pivotal choice in The Big Leap — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_18_tata',
    ARRAY['career_uncertainty', 'family_pressure'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Ratan Tata at age 18 navigating the defiant blueprint: At 18, Ratan chose architecture over his father\',
    ARRAY['ratan tata', 'the defiant blueprint', 'ratan tata age 18', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Ratan Tata at age 18 faced a pivotal choice in The Defiant Blueprint — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Mark Zuckerberg at age 19 navigating the visionary: At 19, Mark had to choose between Harvard and his side project.',
    ARRAY['mark zuckerberg', 'the visionary', 'mark zuckerberg age 19', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Mark Zuckerberg at age 19 faced a pivotal choice in The Visionary — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_neeraj',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['isolation'],
    ARRAY['lonely'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Neeraj Chopra at age 19 navigating the lonely flight: At 19, Neeraj chose isolation over fame.',
    ARRAY['neeraj chopra', 'the lonely flight', 'neeraj chopra age 19', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Neeraj Chopra at age 19 faced a pivotal choice in The Lonely Flight — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_shubman',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['high_stakes_pressure'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Shubman Gill at age 19 navigating the prince: At 19, Shubman was named Player of the Tournament in the U-19 World Cup.',
    ARRAY['shubman gill', 'the prince', 'shubman gill age 19', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Shubman Gill at age 19 faced a pivotal choice in The Prince — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_sachin',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['motivated'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Sachin Tendulkar at age 19 navigating the trial of fire: At 19, you must face the most lethal fast bowlers on Earth.',
    ARRAY['sachin tendulkar', 'the trial of fire', 'sachin tendulkar age 19', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Sachin Tendulkar at age 19 faced a pivotal choice in The Trial of Fire — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_sundar',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['high_stakes_pressure'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Sundar Pichai at age 19 navigating the divided mind: At 19, the pressure of IIT threatens to crush your curiosity.',
    ARRAY['sundar pichai', 'the divided mind', 'sundar pichai age 19', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Sundar Pichai at age 19 faced a pivotal choice in The Divided Mind — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_srk',
    ARRAY['family_pressure'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Shah Rukh Khan at age 19 navigating a stage for grief: At 19, you lose your father and immerse yourself in the chaotic world of theatre.',
    ARRAY['shah rukh khan', 'a stage for grief', 'shah rukh khan age 19', 'family_pressure'],
    'support',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 19 faced a pivotal choice in A Stage For Grief — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_srk_2',
    ARRAY['family_pressure', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Shah Rukh Khan at age 19 navigating leave delhi or stay: At 19, SRK must choose between family duty and the pull of Mumbai.',
    ARRAY['shah rukh khan', 'leave delhi or stay', 'shah rukh khan age 19', 'family_pressure'],
    'support',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 19 faced a pivotal choice in Leave Delhi or Stay — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_prajakta',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Prajakta Koli at age 20 navigating the 2 am panic: At 20, Prajakta quit her 10-year dream job for a risky YouTube career.',
    ARRAY['prajakta koli', 'the 2 am panic', 'prajakta koli age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Prajakta Koli at age 20 faced a pivotal choice in The 2 AM Panic — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_selena',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Selena Gomez at age 20 navigating the invisible war: At 20, Selena battled Lupus behind the perfect pop-star facade.',
    ARRAY['selena gomez', 'the invisible war', 'selena gomez age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Selena Gomez at age 20 faced a pivotal choice in The Invisible War — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_kobe',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Kobe Bryant at age 20 navigating the mamba: At 20, Kobe chose the gym over the party.',
    ARRAY['kobe bryant', 'the mamba', 'kobe bryant age 20', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Kobe Bryant at age 20 faced a pivotal choice in The Mamba — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_nv_sir',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Nitin Vijay (NV Sir) at age 20 navigating the educator\: At 20, NV Sir chose teaching over immediate financial relief.',
    ARRAY['nitin vijay (nv sir)', 'the educator\', 'nitin vijay (nv sir) age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Nitin Vijay (NV Sir) at age 20 faced a pivotal choice in The Educator\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_music',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Taylor Swift at age 20 navigating the soloist: At 20, Taylor faced critics who said she had ghostwriters.',
    ARRAY['taylor swift', 'the soloist', 'taylor swift age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Taylor Swift at age 20 faced a pivotal choice in The Soloist — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_art',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Frida Kahlo at age 20 navigating the icon: At 20, Frida painted from her bed in pain.',
    ARRAY['frida kahlo', 'the icon', 'frida kahlo age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Frida Kahlo at age 20 faced a pivotal choice in The Icon — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'scenario_arnold_awol',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Arnold Schwarzenegger at age 20 navigating the awol gamble: At 20, Arnold escaped the army to chase a dream.',
    ARRAY['arnold schwarzenegger', 'the awol gamble', 'arnold schwarzenegger age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Arnold Schwarzenegger at age 20 faced a pivotal choice in The AWOL Gamble — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'scenario_hawking_diagnosis',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Stephen Hawking at age 20 navigating the death sentence: At 20, Stephen was given 2 years to live.',
    ARRAY['stephen hawking', 'the death sentence', 'stephen hawking age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Stephen Hawking at age 20 faced a pivotal choice in The Death Sentence — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_literature',
    ARRAY['starting_something'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Mary Shelley at age 20 navigating the monster\: At 20, Mary wrote the first sci-fi novel during a storm.',
    ARRAY['mary shelley', 'the monster\', 'mary shelley age 20', 'starting_something'],
    'support',
    'You are dealing with {user_problem}. Mary Shelley at age 20 faced a pivotal choice in The Monster\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_cinema',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Steven Spielberg at age 20 navigating the director: At 20, Steven sneaked into Universal Studios and pretended he worked there.',
    ARRAY['steven spielberg', 'the director', 'steven spielberg age 20', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Steven Spielberg at age 20 faced a pivotal choice in The Director — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20',
    ARRAY['confidence_low'],
    ARRAY['lack_of_direction'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Bill Gates at age 20 navigating the architect: At 20, Bill saw the future and had to bluff his way into it.',
    ARRAY['bill gates', 'the architect', 'bill gates age 20', 'confidence_low'],
    'support',
    'You are dealing with {user_problem}. Bill Gates at age 20 faced a pivotal choice in The Architect — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_sheeran_1',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Ed Sheeran at age 21 navigating the photo she might see: At 21, you must choose how to handle the painful intersection of a recent breakup and sudden public attention.',
    ARRAY['ed sheeran', 'the photo she might see', 'ed sheeran age 21', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Ed Sheeran at age 21 faced a pivotal choice in The Photo She Might See — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_sheeran_2',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'pivot',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Ed Sheeran at age 21 navigating the people that still feel like home: At 21, you must decide what success is allowed to cost you in your personal life.',
    ARRAY['ed sheeran', 'the people that still feel like home', 'ed sheeran age 21', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Ed Sheeran at age 21 faced a pivotal choice in The People That Still Feel Like Home — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_selena_1',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Selena Gomez at age 21 navigating when everyone has an opinion: At 21, you must choose how to handle the painful intersection of a recent relationship and sudden public attention.',
    ARRAY['selena gomez', 'when everyone has an opinion', 'selena gomez age 21', 'big_decision'],
    'support',
    'You are dealing with {user_problem}. Selena Gomez at age 21 faced a pivotal choice in When Everyone Has an Opinion — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_selena_2',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Selena Gomez at age 21 navigating your own name: At 21, you must decide how much of the person people know is actually the person you want to become.',
    ARRAY['selena gomez', 'your own name', 'selena gomez age 21', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Selena Gomez at age 21 faced a pivotal choice in Your Own Name — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_tanmay_1',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Tanmay Bhat at age 21 navigating should i really do this?: At 21, Tanmay Bhat enters the Mumbai stand-up comedy circuit, deciding how seriously to take his talent before having proof it will work.',
    ARRAY['tanmay bhat', 'should i really do this?', 'tanmay bhat age 21', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Tanmay Bhat at age 21 faced a pivotal choice in Should I Really Do This? — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_tanmay_2',
    ARRAY['starting_something'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Tanmay Bhat at age 21 navigating the five minutes: At 21, Tanmay Bhat gets his first major breakthrough opportunity at the Weirdass Ham-ateur Night competition in Mumbai.',
    ARRAY['tanmay bhat', 'the five minutes', 'tanmay bhat age 21', 'starting_something'],
    'support',
    'You are dealing with {user_problem}. Tanmay Bhat at age 21 faced a pivotal choice in The Five Minutes — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_michael_1',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence', 'understand_myself'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Michael Jackson at age 21 navigating not just the jackson 5: At 21, Michael Jackson enters the Off the Wall era in Los Angeles, deciding how to shape his adult solo musical identity with Quincy Jones.',
    ARRAY['michael jackson', 'not just the jackson 5', 'michael jackson age 21', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Michael Jackson at age 21 faced a pivotal choice in Not Just the Jackson 5 — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_michael_2',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Michael Jackson at age 21 navigating good enough or your best?: At 21, as the music takes shape, Michael Jackson faces the tension between continuous refinement and releasing his work.',
    ARRAY['michael jackson', 'good enough or your best?', 'michael jackson age 21', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Michael Jackson at age 21 faced a pivotal choice in Good Enough or Your Best? — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21_srk',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Shah Rukh Khan at age 21 navigating the role that could destroy you: At 21, SRK faces a villain role that could define or end his career.',
    ARRAY['shah rukh khan', 'the role that could destroy you', 'shah rukh khan age 21', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 21 faced a pivotal choice in The Role That Could Destroy You — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_21',
    ARRAY['career_uncertainty', 'starting_something'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Steve Jobs at age 21 navigating the rebel: At 21, Steve started a company in a garage with no money.',
    ARRAY['steve jobs', 'the rebel', 'steve jobs age 21', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Steve Jobs at age 21 faced a pivotal choice in The Rebel — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Walt Disney at age 22 navigating the dreamer: At 22, Walt lost everything and drew a mouse on a train.',
    ARRAY['walt disney', 'the dreamer', 'walt disney age 22', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Walt Disney at age 22 faced a pivotal choice in The Dreamer — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_michael',
    ARRAY['career_uncertainty', 'starting_something', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Michael Jackson at age 22 navigating the life you built: At 22, Michael must balance the Triumph Tour with his brothers and his rising solo aspirations.',
    ARRAY['michael jackson', 'the life you built', 'michael jackson age 22', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Michael Jackson at age 22 faced a pivotal choice in The Life You Built — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_ashneer',
    ARRAY['career_uncertainty'],
    ARRAY['lack_of_direction'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Ashneer Grover at age 22 navigating the next degree: At 22, Ashneer Grover stands between IIT Delhi and IIM Ahmedabad, deciding how to shape his career direction.',
    ARRAY['ashneer grover', 'the next degree', 'ashneer grover age 22', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Ashneer Grover at age 22 faced a pivotal choice in The Next Degree — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_bhuvan',
    ARRAY['career_uncertainty', 'identity_question', 'starting_something', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Bhuvan Bam at age 22 navigating when the phone started working: At 22, Bhuvan Bam must choose between his original craft of music and the sudden explosive growth of BB Ki Vines.',
    ARRAY['bhuvan bam', 'when the phone started working', 'bhuvan bam age 22', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Bhuvan Bam at age 22 faced a pivotal choice in When the Phone Started Working — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_ronaldo',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['high_stakes_pressure'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Cristiano Ronaldo at age 22 navigating the price of becoming complete: At 22, Cristiano Ronaldo faces intense pressure to transform from a flamboyant young winger into a complete, decisive superstar.',
    ARRAY['cristiano ronaldo', 'the price of becoming complete', 'cristiano ronaldo age 22', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Cristiano Ronaldo at age 22 faced a pivotal choice in The Price of Becoming Complete — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_ranveer',
    ARRAY['exam_pressure'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Ranveer Singh at age 22 navigating the role you can\: At 22, Ranveer Singh returns to Mumbai after studying in the US, figuring out how to build a runway toward acting.',
    ARRAY['ranveer singh', 'the role you can\', 'ranveer singh age 22', 'exam_pressure'],
    'challenge',
    'You are dealing with {user_problem}. Ranveer Singh at age 22 faced a pivotal choice in The Role You Can\ — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_alia',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Alia Bhatt at age 22 navigating more than a star: At 22, Alia Bhatt faces rising expectations after early success, deciding how to stretch her range beyond early acclaim.',
    ARRAY['alia bhatt', 'more than a star', 'alia bhatt age 22', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Alia Bhatt at age 22 faced a pivotal choice in More Than a Star — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_bhagat',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Bhagat Singh at age 22 navigating the price of a voice: At 22, Bhagat Singh fights for political prisoner rights from inside Lahore Central Jail and turns the court into a platform.',
    ARRAY['bhagat singh', 'the price of a voice', 'bhagat singh age 22', 'identity_question'],
    'continue',
    'You are dealing with {user_problem}. Bhagat Singh at age 22 faced a pivotal choice in The Price of a Voice — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_tanmay_1',
    ARRAY['starting_something', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Tanmay Bhat at age 22 navigating just 200 people: At 22, Tanmay Bhat and Gursimran Khamba start the All India Bakchod podcast, aiming for 200 people in a room before knowing how big it would become.',
    ARRAY['tanmay bhat', 'just 200 people', 'tanmay bhat age 22', 'starting_something'],
    'continue',
    'You are dealing with {user_problem}. Tanmay Bhat at age 22 faced a pivotal choice in Just 200 People — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_tanmay_2',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Tanmay Bhat at age 22 navigating what if we go bigger?: At 22, the small podcast experiment begins exceeding original expectations as audiences grow.',
    ARRAY['tanmay bhat', 'what if we go bigger?', 'tanmay bhat age 22', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Tanmay Bhat at age 22 faced a pivotal choice in What If We Go Bigger? — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_23_srk',
    ARRAY['career_uncertainty', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s', 'mid_20s'],
    18,
    30,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Shah Rukh Khan at age 23 navigating gauri or career: At 23, SRK must choose between love and the career opportunity of a lifetime.',
    ARRAY['shah rukh khan', 'gauri or career', 'shah rukh khan age 23', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 23 faced a pivotal choice in Gauri or Career — where {trait} guided their path.',
    true,
    'aya_plus',
    NOW(),
    NOW()
),
(
    'lvl_age_23',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['motivated'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s', 'mid_20s'],
    18,
    30,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Oprah Winfrey at age 23 navigating the voice: At 23, Oprah was fired for being too emotional. It was a gift.',
    ARRAY['oprah winfrey', 'the voice', 'oprah winfrey age 23', 'identity_question'],
    'continue',
    'You are dealing with {user_problem}. Oprah Winfrey at age 23 faced a pivotal choice in The Voice — where {trait} guided their path.',
    true,
    'aya_plus',
    NOW(),
    NOW()
),
(
    'scenario_upsc_tina_college',
    ARRAY['exam_pressure', 'big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s', 'mid_20s'],
    18,
    30,
    'empathy',
    '{"empathy":0.95,"vision":0.85,"leadership":0.8,"risk":0.75,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Tina Dabi at age 24 navigating the college sacrifice: At 21, Tina had to choose between social life and The Hindu.',
    ARRAY['tina dabi', 'the college sacrifice', 'tina dabi age 24', 'exam_pressure'],
    'continue',
    'You are dealing with {user_problem}. Tina Dabi at age 24 faced a pivotal choice in The College Sacrifice — where {trait} guided their path.',
    true,
    'aya_plus',
    NOW(),
    NOW()
),
(
    'lvl_age_25_srk',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s', 'mid_20s'],
    18,
    30,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'pivot',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'indian',
    'A story about Shah Rukh Khan at age 25 navigating mumbai is eating me alive: At 25, SRK is running out of money in Mumbai. One bet could change everything.',
    ARRAY['shah rukh khan', 'mumbai is eating me alive', 'shah rukh khan age 25', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. Shah Rukh Khan at age 25 faced a pivotal choice in Mumbai Is Eating Me Alive — where {trait} guided their path.',
    true,
    'aya_plus',
    NOW(),
    NOW()
),
(
    'lvl_age_19_billie',
    ARRAY['feeling_stuck'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'creativity',
    '{"creativity":0.95,"vision":0.85,"empathy":0.8,"risk":0.7,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Billie Eilish at age 19 navigating fame is eating me alive: At 19, Billie won 5 Grammys and was falling apart inside.',
    ARRAY['billie eilish', 'fame is eating me alive', 'billie eilish age 19', 'feeling_stuck'],
    'support',
    'You are dealing with {user_problem}. Billie Eilish at age 19 faced a pivotal choice in Fame Is Eating Me Alive — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_mrbeast',
    ARRAY['exam_pressure', 'confidence_low'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'pivot',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about MrBeast at age 19 navigating drop out or keep uploading: At 19, Jimmy had 30K subscribers and a ridiculous idea. College apps were due tomorrow.',
    ARRAY['mrbeast', 'drop out or keep uploading', 'mrbeast age 19', 'exam_pressure'],
    'support',
    'You are dealing with {user_problem}. MrBeast at age 19 faced a pivotal choice in Drop Out or Keep Uploading — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_ritesh',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Ritesh Agarwal at age 19 navigating the dropout founder: At 19, Ritesh had ₹2,000, a dropout status, and a world-changing idea.',
    ARRAY['ritesh agarwal', 'the dropout founder', 'ritesh agarwal age 19', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Ritesh Agarwal at age 19 faced a pivotal choice in The Dropout Founder — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_ali',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Muhammad Ali at age 19 navigating throw the medal away: At 19, Ali won Olympic gold — then was refused service at a restaurant because of his race.',
    ARRAY['muhammad ali', 'throw the medal away', 'muhammad ali age 19', 'career_uncertainty'],
    'support',
    'You are dealing with {user_problem}. Muhammad Ali at age 19 faced a pivotal choice in Throw The Medal Away — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_20_dhruv',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Dhruv Rathee at age 20 navigating germany or india: At 20, an engineering scholar in Germany felt India needed his voice more than his degree.',
    ARRAY['dhruv rathee', 'germany or india', 'dhruv rathee age 20', 'identity_question'],
    'challenge',
    'You are dealing with {user_problem}. Dhruv Rathee at age 20 faced a pivotal choice in Germany or India — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_falguni',
    ARRAY['career_uncertainty'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['motivated'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'leadership',
    '{"leadership":0.95,"risk":0.85,"vision":0.8,"creativity":0.7,"empathy":0.6}'::jsonb,
    'overcome',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'indian',
    'A story about Falguni Nayar at age 19 navigating science or business: At 19 at IIM Ahmedabad, Falguni had a fire inside her — but the world said wait.',
    ARRAY['falguni nayar', 'science or business', 'falguni nayar age 19', 'career_uncertainty'],
    'challenge',
    'You are dealing with {user_problem}. Falguni Nayar at age 19 faced a pivotal choice in Science or Business — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_19_tesla',
    ARRAY['identity_question'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"vision":0.95,"creativity":0.8,"risk":0.7,"leadership":0.65,"empathy":0.5}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    3,
    4,
    'modern',
    'global',
    'A story about Nikola Tesla at age 19 navigating trust your visions: At 19, Tesla\',
    ARRAY['nikola tesla', 'trust your visions', 'nikola tesla age 19', 'identity_question'],
    'support',
    'You are dealing with {user_problem}. Nikola Tesla at age 19 faced a pivotal choice in Trust Your Visions — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_22_rani_lakshmibai',
    ARRAY['feeling_stuck'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s'],
    16,
    25,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about Rani Lakshmibai at age 22 navigating the silent palace: At 22, the Queen of Jhansi faces the death of her infant son and an empire waiting to take her kingdom.',
    ARRAY['rani lakshmibai', 'the silent palace', 'rani lakshmibai age 22', 'feeling_stuck'],
    'continue',
    'You are dealing with {user_problem}. Rani Lakshmibai at age 22 faced a pivotal choice in The Silent Palace — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_11_virat_kohli',
    ARRAY['big_decision'],
    ARRAY['uncertainty', 'proving_oneself'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['teen'],
    13,
    18,
    'risk',
    '{"risk":0.9,"leadership":0.85,"vision":0.75,"empathy":0.6,"creativity":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    2,
    4,
    'modern',
    'indian',
    'A story about Virat Kohli at age 11 navigating the extra hour: At 11, young Virat Kohli trains at West Delhi Cricket Academy, facing decisions between raw instinct and disciplined technical correction.',
    ARRAY['virat kohli', 'the extra hour', 'virat kohli age 11', 'big_decision'],
    'challenge',
    'You are dealing with {user_problem}. Virat Kohli at age 11 faced a pivotal choice in The Extra Hour — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
),
(
    'lvl_age_25',
    ARRAY['career_uncertainty', 'identity_question'],
    ARRAY['isolation'],
    ARRAY['anxious', 'hopeful'],
    ARRAY['find_direction', 'build_confidence'],
    ARRAY['early_20s', 'mid_20s'],
    18,
    30,
    'vision',
    '{"risk":0.6,"creativity":0.6,"vision":0.8,"empathy":0.6,"leadership":0.6}'::jsonb,
    'persist',
    ARRAY['courage', 'resilience', 'identity'],
    4,
    4,
    'modern',
    'global',
    'A story about J.K. Rowling at age 25 navigating the storyteller: At 25, J.K. Rowling got the idea for Harry Potter on a delayed train.',
    ARRAY['j.k. rowling', 'the storyteller', 'j.k. rowling age 25', 'career_uncertainty'],
    'continue',
    'You are dealing with {user_problem}. J.K. Rowling at age 25 faced a pivotal choice in The Storyteller — where {trait} guided their path.',
    true,
    'aya_plus',
    NOW(),
    NOW()
),
(
    'lvl_age_20_modi',
    ARRAY['purpose', 'starting_with_little', 'discipline', 'career_uncertainty'],
    ARRAY['unfulfilled_by_work', 'spiritual_vs_practical', 'security_vs_service', 'uncertainty'],
    ARRAY['restless', 'seeking', 'determined', 'conflicted'],
    ARRAY['find_direction', 'build_discipline', 'courage_to_commit'],
    ARRAY['early_20s'],
    16,
    25,
    'purpose',
    '{"leadership":0.98,"discipline":0.98,"vision":0.95,"risk":0.9,"resilience":0.95,"empathy":0.85,"creativity":0.8}'::jsonb,
    'action_step',
    ARRAY['purpose', 'discipline', 'service', 'courage', 'resilience'],
    3,
    5,
    'modern',
    'indian',
    'A story about Narendra Modi at age 20 navigating the canteen and the calling: At 20, working in a bus depot canteen after two years in the Himalayas, torn between monastic life, business security, and full-time national service.',
    ARRAY['narendra modi', 'the canteen and the calling', 'narendra modi age 20', 'purpose', 'starting_with_little', 'discipline', 'pracharak', 'canteen'],
    'challenge',
    'You are dealing with {user_problem}. Narendra Modi at age 20 faced a pivotal choice in The Canteen and the Calling — where {trait} guided their path.',
    false,
    NULL,
    NOW(),
    NOW()
)
ON CONFLICT (story_id) DO UPDATE SET
    situation_tags = EXCLUDED.situation_tags,
    problem_tags = EXCLUDED.problem_tags,
    emotional_tags = EXCLUDED.emotional_tags,
    intent_tags = EXCLUDED.intent_tags,
    life_stage_tags = EXCLUDED.life_stage_tags,
    age_min = EXCLUDED.age_min,
    age_max = EXCLUDED.age_max,
    dominant_trait = EXCLUDED.dominant_trait,
    trait_affinity = EXCLUDED.trait_affinity,
    resolution_archetype = EXCLUDED.resolution_archetype,
    lesson_tags = EXCLUDED.lesson_tags,
    difficulty = EXCLUDED.difficulty,
    relatability = EXCLUDED.relatability,
    era = EXCLUDED.era,
    cultural_context = EXCLUDED.cultural_context,
    semantic_description = EXCLUDED.semantic_description,
    trigger_phrases = EXCLUDED.trigger_phrases,
    best_for_mode = EXCLUDED.best_for_mode,
    why_this_story_template = EXCLUDED.why_this_story_template,
    is_premium = EXCLUDED.is_premium,
    premium_tier = EXCLUDED.premium_tier,
    updated_at = NOW();
