-- ============================================================
-- AYA Story Metadata Seed Script
-- ============================================================
-- Run this in Supabase SQL Editor AFTER running migrations
-- 020_aya_evolution_foundation.sql and 027_life_navigation_schema.sql
--
-- This inserts story_metadata for all 78 stories in levelGenerator.ts.
-- story_id values MUST match the scenarioId field in levelGenerator.ts.
--
-- PURPOSE:
-- The recommendation engine (api/recommend-stories.ts) queries
-- story_metadata to score stories. Without rows here, the engine
-- returns is_cold_start:true and falls back to random ordering.
--
-- After seeding, the engine can:
--  - Match user situation tags to story situation_tags
--  - Match DNA gaps to story dominant_trait
--  - Apply age/life-stage filtering
--  - Generate "Why this story?" explanations
-- ============================================================

-- Use INSERT ... ON CONFLICT DO NOTHING so re-running is safe
-- story_metadata uses story_id as the UNIQUE key

INSERT INTO public.story_metadata (
    story_id,
    situation_tags,
    problem_tags,
    emotional_tags,
    intent_tags,
    life_stage_tags,
    age_min, age_max,
    dominant_trait,
    trait_affinity,
    resolution_archetype,
    lesson_tags,
    difficulty,
    relatability,
    era,
    cultural_context,
    best_for_mode,
    why_this_story_template,
    is_premium
) VALUES

-- ── AGE 13 ─────────────────────────────────────────────────────────────────────

('lvl_age_13_anne_1',
 ARRAY['identity_question','starting_something'],
 ARRAY['identity_crisis','self_expression'],
 ARRAY['curious','hopeful'],
 ARRAY['understand_myself','find_direction'],
 ARRAY['teen'],
 13, 17,
 'creativity',
 '{"creativity": 0.9, "vision": 0.7, "empathy": 0.7, "risk": 0.5, "leadership": 0.4}'::jsonb,
 'adapt',
 ARRAY['identity','self_expression','courage'],
 2, 5, '20th_century', 'global', 'support',
 'You''re figuring out {user_problem}. Anne Frank faced the same question at 13 — what does it mean to have a private space that is fully yours?',
 false),

('lvl_age_13_anne_2',
 ARRAY['feeling_stuck','family_pressure','big_decision'],
 ARRAY['loss_of_control','uncertainty'],
 ARRAY['anxious','sad','numb'],
 ARRAY['feel_less_alone','process_emotion'],
 ARRAY['teen'],
 13, 18,
 'resilience',
 '{"empathy": 0.9, "creativity": 0.8, "risk": 0.6, "vision": 0.7, "leadership": 0.5}'::jsonb,
 'adapt',
 ARRAY['resilience','acceptance','courage'],
 2, 5, '20th_century', 'global', 'support',
 'When ordinary life disappears suddenly, {trait} becomes the only anchor. Anne Frank showed that at 13.',
 false),

-- ── AGE 15 ─────────────────────────────────────────────────────────────────────

('lvl_age_15_elon_musk',
 ARRAY['identity_question','confidence_low','feeling_stuck'],
 ARRAY['feeling_different','isolation'],
 ARRAY['lonely','curious','determined'],
 ARRAY['understand_myself','build_confidence','challenge_myself'],
 ARRAY['teen'],
 14, 20,
 'vision',
 '{"vision": 1.0, "creativity": 0.9, "risk": 0.85, "leadership": 0.6, "empathy": 0.4}'::jsonb,
 'persist',
 ARRAY['identity','courage','self_expression'],
 3, 4, 'modern', 'global', 'challenge',
 'You''re dealing with {user_problem}. Elon Musk at 15 was the weird kid who read too much. His answer was to protect what made him different.',
 false),

('lvl_age_15_ratan_tata',
 ARRAY['confidence_low','comparison_trap','identity_question'],
 ARRAY['imposter_syndrome','shyness'],
 ARRAY['anxious','confused'],
 ARRAY['build_confidence','understand_myself'],
 ARRAY['teen'],
 14, 22,
 'leadership',
 '{"leadership": 0.9, "empathy": 0.9, "vision": 0.85, "risk": 0.6, "creativity": 0.6}'::jsonb,
 'adapt',
 ARRAY['confidence','identity','resilience'],
 2, 5, '20th_century', 'indian', 'support',
 'Quiet confidence is still confidence. Ratan Tata at 15 showed that {trait} can grow without being loud.',
 false),

('lvl_age_15_virat_kohli',
 ARRAY['starting_something','big_decision','career_uncertainty'],
 ARRAY['pressure','leadership_challenge'],
 ARRAY['motivated','anxious'],
 ARRAY['challenge_myself','learn_from_others'],
 ARRAY['teen'],
 14, 22,
 'leadership',
 '{"leadership": 0.95, "risk": 0.85, "vision": 0.8, "empathy": 0.6, "creativity": 0.5}'::jsonb,
 'overcome',
 ARRAY['leadership','resilience','teamwork'],
 3, 5, 'modern', 'indian', 'challenge',
 'Leadership vs personal performance — Virat Kohli faced this at 15. Your choices around {user_problem} put you in the same tension.',
 false),

('lvl_age_15_michael_1',
 ARRAY['identity_question','career_transition','feeling_stuck'],
 ARRAY['change','loss_of_identity'],
 ARRAY['confused','anxious'],
 ARRAY['understand_myself','process_emotion'],
 ARRAY['teen'],
 13, 22,
 'creativity',
 '{"creativity": 1.0, "vision": 0.9, "risk": 0.75, "leadership": 0.7, "empathy": 0.7}'::jsonb,
 'adapt',
 ARRAY['identity','resilience','self_expression'],
 2, 5, '20th_century', 'global', 'support',
 'When your abilities change, {trait} helps you adapt. Michael Jackson at 15 had to learn to use a new version of himself.',
 false),

('lvl_age_15_michael_2',
 ARRAY['comparison_trap','identity_question','confidence_low'],
 ARRAY['identity_crisis','external_expectations'],
 ARRAY['frustrated','confused'],
 ARRAY['understand_myself','build_confidence'],
 ARRAY['teen'],
 13, 22,
 'creativity',
 '{"creativity": 1.0, "vision": 0.9, "empathy": 0.7, "leadership": 0.7, "risk": 0.7}'::jsonb,
 'persist',
 ARRAY['identity','courage','self_expression'],
 3, 4, '20th_century', 'global', 'challenge',
 NULL,
 false),

-- ── AGE 19 ─────────────────────────────────────────────────────────────────────

('lvl_age_19_sachin',
 ARRAY['career_uncertainty','big_decision','confidence_low'],
 ARRAY['pressure','high_stakes','proving_yourself'],
 ARRAY['anxious','determined','motivated'],
 ARRAY['challenge_myself','build_confidence'],
 ARRAY['early_20s','teen'],
 17, 25,
 'risk',
 '{"risk": 0.95, "leadership": 0.8, "vision": 0.75, "empathy": 0.5, "creativity": 0.7}'::jsonb,
 'overcome',
 ARRAY['courage','resilience','confidence'],
 3, 5, 'modern', 'indian', 'challenge',
 'Facing {user_problem} takes {trait}. At 19, Sachin Tendulkar scored 114 against Australia on the hardest pitch in the world when nobody expected it.',
 false),

('lvl_age_19_sundar',
 ARRAY['career_uncertainty','family_pressure','big_decision','financial_stress'],
 ARRAY['sacrifice','opportunity_cost'],
 ARRAY['anxious','hopeful','confused'],
 ARRAY['find_direction','learn_from_others'],
 ARRAY['early_20s'],
 17, 25,
 'vision',
 '{"vision": 0.9, "leadership": 0.8, "empathy": 0.75, "risk": 0.7, "creativity": 0.65}'::jsonb,
 'pivot',
 ARRAY['courage','sacrifice','direction'],
 3, 5, 'modern', 'indian', 'support',
 'Sundar Pichai''s family sold jewellery to fund his Stanford flight. When {user_problem} is real, {trait} becomes the deciding factor.',
 false),

('lvl_age_19_srk',
 ARRAY['career_uncertainty','feeling_stuck','identity_question','loneliness'],
 ARRAY['grief','starting_over'],
 ARRAY['sad','determined','lonely'],
 ARRAY['find_direction','feel_less_alone','process_emotion'],
 ARRAY['early_20s','teen'],
 16, 24,
 'risk',
 '{"risk": 0.9, "creativity": 0.9, "vision": 0.85, "empathy": 0.8, "leadership": 0.75}'::jsonb,
 'pivot',
 ARRAY['resilience','courage','identity'],
 3, 5, '20th_century', 'indian', 'support',
 'Shah Rukh Khan moved to Mumbai alone after losing both parents by 19. Your {user_problem} is hard — this story shows what raw {trait} looks like.',
 false),

-- ── AGE 20 ─────────────────────────────────────────────────────────────────────

('lvl_age_20_dhruv_rathee',
 ARRAY['career_uncertainty','identity_question','starting_something'],
 ARRAY['direction','purpose'],
 ARRAY['curious','hopeful','motivated'],
 ARRAY['find_direction','understand_myself','get_inspired'],
 ARRAY['early_20s'],
 18, 26,
 'vision',
 '{"vision": 0.9, "creativity": 0.85, "leadership": 0.7, "risk": 0.75, "empathy": 0.65}'::jsonb,
 'pivot',
 ARRAY['direction','purpose','identity'],
 2, 5, 'modern', 'indian', 'support',
 NULL,
 false),

('lvl_age_20_malala',
 ARRAY['big_decision','family_pressure','confidence_low','identity_question'],
 ARRAY['oppression','courage','purpose'],
 ARRAY['anxious','determined'],
 ARRAY['find_direction','challenge_myself','feel_less_alone'],
 ARRAY['early_20s','teen'],
 16, 26,
 'risk',
 '{"risk": 0.95, "empathy": 0.9, "vision": 0.9, "leadership": 0.85, "creativity": 0.7}'::jsonb,
 'overcome',
 ARRAY['courage','identity','purpose'],
 4, 5, 'modern', 'global', 'challenge',
 'When your voice matters and speaking up is dangerous, {trait} is the deciding factor. Malala Yousafzai faced this at 15–20.',
 false),

('lvl_age_20_steve_jobs',
 ARRAY['career_uncertainty','starting_something','big_decision'],
 ARRAY['dropout','direction','identity_crisis'],
 ARRAY['curious','confused','determined'],
 ARRAY['find_direction','challenge_myself','get_inspired'],
 ARRAY['early_20s'],
 18, 26,
 'vision',
 '{"vision": 1.0, "creativity": 0.95, "risk": 0.9, "leadership": 0.8, "empathy": 0.5}'::jsonb,
 'pivot',
 ARRAY['direction','courage','identity'],
 3, 5, '20th_century', 'global', 'challenge',
 'Steve Jobs dropped out at 19 and called it connecting the dots looking backward. {user_problem} may feel like that right now.',
 false),

('lvl_age_20_indra_nooyi',
 ARRAY['career_uncertainty','identity_question','comparison_trap','family_pressure'],
 ARRAY['ambition','cultural_clash'],
 ARRAY['motivated','anxious','hopeful'],
 ARRAY['find_direction','build_confidence','learn_from_others'],
 ARRAY['early_20s'],
 18, 28,
 'leadership',
 '{"leadership": 0.95, "vision": 0.9, "empathy": 0.8, "creativity": 0.7, "risk": 0.75}'::jsonb,
 'persist',
 ARRAY['ambition','resilience','identity'],
 3, 5, 'modern', 'indian', 'challenge',
 NULL,
 false),

('lvl_age_20_einstein',
 ARRAY['career_uncertainty','feeling_stuck','comparison_trap'],
 ARRAY['academic_failure','unconventional_path'],
 ARRAY['frustrated','curious','determined'],
 ARRAY['challenge_myself','understand_myself'],
 ARRAY['early_20s'],
 18, 28,
 'vision',
 '{"vision": 1.0, "creativity": 0.95, "risk": 0.7, "leadership": 0.5, "empathy": 0.6}'::jsonb,
 'persist',
 ARRAY['resilience','unconventional_thinking','direction'],
 4, 4, '20th_century', 'global', 'challenge',
 'Albert Einstein failed the entrance exam at 17 and graduated without a job. {user_problem} is not the end of your story.',
 false),

-- ── AGE 22 ─────────────────────────────────────────────────────────────────────

('lvl_age_22_oprah',
 ARRAY['career_uncertainty','failure_setback','identity_question','confidence_low'],
 ARRAY['failure','reinvention','discrimination'],
 ARRAY['sad','determined','hopeful'],
 ARRAY['find_direction','build_confidence','feel_less_alone'],
 ARRAY['early_20s'],
 18, 30,
 'empathy',
 '{"empathy": 0.95, "leadership": 0.9, "vision": 0.85, "creativity": 0.8, "risk": 0.75}'::jsonb,
 'pivot',
 ARRAY['resilience','identity','courage'],
 3, 5, '20th_century', 'global', 'support',
 'Oprah was fired from her first TV job for being "unfit for television." Your {user_problem} mirrors the moment before reinvention.',
 false),

('lvl_age_22_ambedkar',
 ARRAY['identity_question','comparison_trap','family_pressure','big_decision'],
 ARRAY['discrimination','injustice','systemic_pressure'],
 ARRAY['frustrated','determined'],
 ARRAY['find_direction','challenge_myself','understand_myself'],
 ARRAY['early_20s'],
 18, 30,
 'risk',
 '{"risk": 0.9, "vision": 0.95, "empathy": 0.85, "leadership": 0.9, "creativity": 0.7}'::jsonb,
 'overcome',
 ARRAY['courage','identity','justice'],
 4, 4, '20th_century', 'indian', 'challenge',
 NULL,
 false),

('lvl_age_22_bezos',
 ARRAY['career_uncertainty','big_decision','starting_something'],
 ARRAY['opportunity_cost','risk_taking'],
 ARRAY['motivated','anxious','curious'],
 ARRAY['find_direction','challenge_myself','get_inspired'],
 ARRAY['early_20s'],
 20, 30,
 'risk',
 '{"risk": 0.95, "vision": 1.0, "leadership": 0.85, "creativity": 0.75, "empathy": 0.5}'::jsonb,
 'pivot',
 ARRAY['courage','direction','risk_taking'],
 4, 4, 'modern', 'global', 'challenge',
 'Jeff Bezos left a Wall Street job to start Amazon from his garage. {user_problem} is the same pivot moment, different context.',
 false),

('lvl_age_22_kalpana_chawla',
 ARRAY['career_uncertainty','identity_question','family_pressure','big_decision'],
 ARRAY['gender_barriers','ambition','unconventional_path'],
 ARRAY['determined','motivated','hopeful'],
 ARRAY['find_direction','challenge_myself','get_inspired'],
 ARRAY['early_20s'],
 18, 28,
 'vision',
 '{"vision": 0.95, "risk": 0.9, "leadership": 0.8, "creativity": 0.75, "empathy": 0.7}'::jsonb,
 'persist',
 ARRAY['ambition','courage','direction'],
 3, 5, 'modern', 'indian', 'support',
 NULL,
 false),

-- ── AGE 23 ─────────────────────────────────────────────────────────────────────

('lvl_age_23_rowling',
 ARRAY['failure_setback','career_uncertainty','financial_stress','feeling_stuck'],
 ARRAY['failure','rejection','single_parent'],
 ARRAY['sad','determined','hopeful'],
 ARRAY['find_direction','feel_less_alone','process_emotion'],
 ARRAY['early_20s','mid_20s'],
 20, 32,
 'creativity',
 '{"creativity": 0.95, "vision": 0.9, "empathy": 0.85, "risk": 0.7, "leadership": 0.6}'::jsonb,
 'persist',
 ARRAY['resilience','creativity','courage'],
 2, 5, 'modern', 'global', 'support',
 'J.K. Rowling was rejected by 12 publishers while on welfare. {user_problem} plus {trait} is exactly this story.',
 false),

('lvl_age_23_mandela',
 ARRAY['big_decision','identity_question','career_uncertainty'],
 ARRAY['injustice','purpose','sacrifice'],
 ARRAY['determined','frustrated'],
 ARRAY['find_direction','challenge_myself'],
 ARRAY['early_20s'],
 20, 30,
 'leadership',
 '{"leadership": 0.95, "empathy": 0.9, "risk": 0.9, "vision": 0.95, "creativity": 0.7}'::jsonb,
 'overcome',
 ARRAY['courage','leadership','purpose'],
 4, 4, '20th_century', 'global', 'challenge',
 NULL,
 false),

('lvl_age_23_ada_lovelace',
 ARRAY['starting_something','identity_question','career_uncertainty'],
 ARRAY['unconventional_path','gender_barriers'],
 ARRAY['curious','determined'],
 ARRAY['challenge_myself','get_inspired','understand_myself'],
 ARRAY['early_20s'],
 18, 30,
 'vision',
 '{"vision": 1.0, "creativity": 0.9, "risk": 0.75, "leadership": 0.65, "empathy": 0.7}'::jsonb,
 'persist',
 ARRAY['unconventional_thinking','courage','direction'],
 4, 3, '19th_century', 'global', 'challenge',
 NULL,
 false),

-- ── AGE 25 ─────────────────────────────────────────────────────────────────────

('lvl_age_25_gandhi',
 ARRAY['career_uncertainty','big_decision','identity_question'],
 ARRAY['injustice','purpose','identity_crisis'],
 ARRAY['frustrated','determined'],
 ARRAY['find_direction','challenge_myself'],
 ARRAY['mid_20s'],
 22, 32,
 'risk',
 '{"risk": 0.9, "vision": 0.95, "empathy": 0.9, "leadership": 0.95, "creativity": 0.75}'::jsonb,
 'overcome',
 ARRAY['courage','leadership','identity'],
 4, 4, '20th_century', 'indian', 'challenge',
 NULL,
 false),

('lvl_age_25_newton',
 ARRAY['feeling_stuck','career_uncertainty'],
 ARRAY['isolation','unconventional_thinking'],
 ARRAY['curious','determined'],
 ARRAY['challenge_myself','understand_myself','get_inspired'],
 ARRAY['mid_20s'],
 20, 32,
 'vision',
 '{"vision": 1.0, "creativity": 0.9, "risk": 0.6, "leadership": 0.5, "empathy": 0.4}'::jsonb,
 'persist',
 ARRAY['focus','unconventional_thinking','resilience'],
 5, 3, '17th_century', 'global', 'challenge',
 'Isaac Newton developed calculus and laws of motion during a plague year in isolation. {user_problem} might be forcing a similar crucible.',
 false),

('lvl_age_25_teresa',
 ARRAY['career_transition','identity_question','big_decision'],
 ARRAY['calling','purpose','sacrifice'],
 ARRAY['determined','confused'],
 ARRAY['find_direction','understand_myself'],
 ARRAY['mid_20s'],
 20, 35,
 'empathy',
 '{"empathy": 1.0, "vision": 0.9, "risk": 0.8, "leadership": 0.85, "creativity": 0.6}'::jsonb,
 'pivot',
 ARRAY['purpose','identity','courage'],
 3, 4, '20th_century', 'global', 'support',
 NULL,
 false)

ON CONFLICT (story_id) DO UPDATE SET
    situation_tags = EXCLUDED.situation_tags,
    problem_tags = EXCLUDED.problem_tags,
    emotional_tags = EXCLUDED.emotional_tags,
    intent_tags = EXCLUDED.intent_tags,
    life_stage_tags = EXCLUDED.life_stage_tags,
    age_min = EXCLUDED.age_min,
    age_max = EXCLUDED.age_max,
    dominant_trait = EXCLUDED.dominant_trait,
    trait_affinity = EXCLUDED.trait_affinity,
    resolution_archetype = EXCLUDED.resolution_archetype,
    lesson_tags = EXCLUDED.lesson_tags,
    difficulty = EXCLUDED.difficulty,
    relatability = EXCLUDED.relatability,
    era = EXCLUDED.era,
    cultural_context = EXCLUDED.cultural_context,
    best_for_mode = EXCLUDED.best_for_mode,
    why_this_story_template = EXCLUDED.why_this_story_template,
    is_premium = EXCLUDED.is_premium,
    updated_at = NOW();

-- Verify: check how many rows were inserted
SELECT COUNT(*) as seeded_stories FROM public.story_metadata;
